#!/bin/bash

echo "
=======================================================
Starting all docker containers except testing.
=======================================================
"

docker-compose up "$@"
