#!/bin/bash

echo "
=======================================================
Starting all docker containers including testing.
=======================================================
"

docker-compose up -d db --build
docker-compose up -d api --build 
docker-compose up -d app --build 
docker-compose up -d nginx --build
docker-compose up test --build
