#!/bin/bash

echo "
=======================================================
Starting all docker containers including testing.
=======================================================
"

docker-compose up -d db
docker-compose up -d api
docker-compose up -d app
docker-compose up -d nginx
docker-compose up test
