#!/bin/bash

echo "
=======================================================
Starting all docker containers except testing.
=======================================================
"

docker-compose up -d db --build
docker-compose up -d api --build
docker-compose up -d app --build
docker-compose up -d nginx --build
